## Development environment

spring:
  jpa.hibernate.ddl-auto: update
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fid123!!
    
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security.core.Authentication: DEBUG
    net.travel.auth: DEBUG
  # file:
    # name: D:\\tmp\\dev-log.txt
    

    